import styles from "@/styles/wrappers/SiteWrapper.module.scss";
import Head from "next/head";
import Footer from "../Footer";
import NavBar from "../NavBar";

interface Props {
  children: React.ReactNode;
  conf: any;
  title: string;
}

const SiteWrapper = ({ children, conf, title }: Props) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          @import
          url("https://fonts.googleapis.com/css2?family=JetBrains+Mono&display=swap");

          @import url("https://fonts.googleapis.com/css2?family=Ubuntu&family=Varela+Round&family=Noto+Serif&family=Martian+Mono&display=swap');
        </style>
      </Head>
      <div className={styles.main}>
        <NavBar conf={conf}/>
          <div className={styles.siteContent}>
            {children}
          </div>
        <Footer conf={conf}/>
      </div>
    </>
  );
};

export default SiteWrapper;
